from __future__ import annotations

from pathlib import Path

from ...models import RuntimeSettings


def write_mdu(
    target_path: Path,
    *,
    model_name: str,
    net_file_name: str,
    ext_file_name: str,
    cross_loc_file_name: str | None,
    cross_def_file_name: str | None,
    structure_file_name: str | None,
    roughness_file_names: tuple[str, ...],
    ini_field_file_name: str | None,
    runtime: RuntimeSettings,
    include_morphology: bool = False,
) -> None:
    target_path.parent.mkdir(parents=True, exist_ok=True)

    refdate = runtime.refdate.strftime("%Y%m%d")
    frict = ";".join(roughness_file_names)
    cross_loc = cross_loc_file_name or ""
    cross_def = cross_def_file_name or ""
    structure_file = structure_file_name or ""
    ini_field = ini_field_file_name or ""
    bedlev_type = 1 if include_morphology else 3

    sediment_block = ""
    if include_morphology:
        sediment_block = """
[sediment]
MorFile                           = mor.mor
SedFile                           = sed.sed
Sedimentmodelnr                   = 4
"""

    content = f"""# Generated by sre_convertor
# model_name = {model_name}
[General]
Program                           = D-Flow FM
fileVersion                       = 1.09
fileType                          = modelDef

[geometry]
NetFile                           = {net_file_name}
IniFieldFile                      = {ini_field}
StructureFile                     = {structure_file}
CrossLocFile                      = {cross_loc}
CrossDefFile                      = {cross_def}
frictFile                         = {frict}
AllowBndAtBifurcation             = 1
WaterLevIni                       = -999.0
BedlevUni                         = -5.0
BedlevType                        = {bedlev_type}
Conveyance2D                      = -1                  # -1: R=HU,0: R=H, 1: R=A/P, 2: K=analytic-1D conv, 3: K=analytic-2D conv

[numerics]
CFLMax                            = 0.7
TimeStepType                      = 2

[physics]
UnifFrictCoef                     = 50
UnifFrictType                     = 0
UnifFrictCoef1D                   = 50

[time]
RefDate                           = {refdate}
Tunit                             = S
TStart                            = {runtime.tstart_seconds}
TStop                             = {runtime.tstop_seconds}
DtUser                            = 3600.0
DtMax                             = 600.0

[external forcing]
ExtForceFile                      =
ExtForceFileNew                   = {ext_file_name}

[output]
OutputDir                         =
HisInterval                       = 3600.0 0.0 0.0
MapInterval                       = 86400.0 0.0 0.0
StatsInterval                     = -60.0
MapFormat                         = 4
{sediment_block}
"""

    target_path.write_text(content, encoding="utf-8")
