from __future__ import annotations

from pathlib import Path

from ...models import MorphodynamicsSummary


def write_morphodynamics_files(
    target_dir: Path,
    summary: MorphodynamicsSummary,
) -> tuple[Path, Path]:
    target_dir.mkdir(parents=True, exist_ok=True)

    mor_path = target_dir / "mor.mor"
    sed_path = target_dir / "sed.sed"

    d50 = summary.representative_d50_m or 0.001

    mor_content = """[MorphologyFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[Morphology]
   MorFac           = 1.0
   MorStt           = 0.0
   Thresh           = 1.0
   BedUpd           = 1
   CmpUpd           = 1
   NeuBcMud         = 0
   NeuBcSand        = 0

[Output]
   Dm               = true
   Dg               = true
   Frac             = true
"""

    sed_content = f"""[SedimentFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[SedimentOverall]
   Cref             = 1.6000000e+003

[Sediment]
   Name             = #Sediment1#
   SedTyp           = bedload
   IniSedThick      = 1.0000000e+000
   RhoSol           = 2.6500000e+003
   TraFrm           = 1
   CDryB            = 1.5900000e+003
   SedDia           = {d50:.7e}
   RouKs            = 0.000
   SusFac           = 0.000
"""

    mor_path.write_text(mor_content, encoding="utf-8")
    sed_path.write_text(sed_content, encoding="utf-8")

    return mor_path, sed_path
