from __future__ import annotations

from pathlib import Path

from ...models import MorphodynamicsSummary, NetworkModel, CrossSectionLocation


def write_morphodynamics_files(
    target_dir: Path,
    summary: MorphodynamicsSummary,
    network: NetworkModel | None = None,
    cross_section_locations: tuple[CrossSectionLocation, ...] | None = None,
) -> tuple[Path, Path, Path, Path]:
    target_dir.mkdir(parents=True, exist_ok=True)

    mor_path = target_dir / "mor.mor"
    sed_path = target_dir / "sed.sed"
    composition_path = target_dir / "mor_composition.ini"
    bed_comp_path = target_dir / "mor.ini"

    fractions = summary.sediment_fractions_d50_m
    if not fractions:
        fallback = summary.representative_d50_m or 0.001
        fractions = (fallback,)

    mor_content = """[MorphologyFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[Morphology]
   MorFac           = 1.0
   MorStt           = 0.0
   Thresh           = 1.0
   BedUpd           = 1
   CmpUpd           = 1
   NeuBcMud         = 0
   NeuBcSand        = 0

[Output]
   Dm               = true
   Dg               = true
   Frac             = true
"""

    sed_blocks: list[str] = []
    for idx, d50 in enumerate(fractions, start=1):
        sed_blocks.extend(
            [
                "[Sediment]",
                f"   Name             = #Sediment{idx}#",
                "   SedTyp           = bedload",
                "   IniSedThick      = 1.0000000e+000",
                "   RhoSol           = 2.6500000e+003",
                "   TraFrm           = 1",
                "   CDryB            = 1.5900000e+003",
                f"   SedDia           = {d50:.7e}",
                "   ACal             = 1.0000000e+000",
                "   RouKs            = 0.000",
                "   SusFac           = 0.000",
                "",
            ]
        )

    sed_content = """[SedimentFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[SedimentOverall]
   Cref             = 1.6000000e+003
""" + "\n".join(sed_blocks)

    composition_lines: list[str] = [
        "[BedCompositionFileInformation]",
        "FileVersion     = 01.00",
        "FileCreatedBy   = sre_convertor",
        "FileCreationDate= autogenerated",
        "",
        "[Layer]",
        "Type = volume fraction",
    ]

    # Generate xyz files if we have spatial data
    if network and cross_section_locations:
        gsd_dir = target_dir / "gsd_ini_str"
        gsd_dir.mkdir(parents=True, exist_ok=True)

        # Create thickness file (uniform 0.5 m per layer)
        thk_xyz_lines: list[str] = []
        for cs_location in cross_section_locations:
            xy = _chainage_to_xy(network, cs_location.branch_id, cs_location.chainage)
            if xy:
                x, y = xy
                thk_xyz_lines.append(f"{x:.15E} {y:.15E} 5.000000000000000E-01")

        if thk_xyz_lines:
            thk_path = gsd_dir / "lyr01_thk.xyz"
            thk_path.write_text("\n".join(thk_xyz_lines) + "\n", encoding="utf-8")
            composition_lines.append("Thick = gsd_ini_str/lyr01_thk.xyz")

        # Create xyz files for each fraction
        for fraction_idx in range(1, len(fractions) + 1):
            xyz_lines: list[str] = []
            for cs_location in cross_section_locations:
                xy = _chainage_to_xy(network, cs_location.branch_id, cs_location.chainage)
                if xy:
                    x, y = xy
                    # Get weight for this fraction from branch composition
                    weight = _get_fraction_weight(summary, cs_location.branch_id, fraction_idx)
                    xyz_lines.append(f"{x:.15E} {y:.15E} {weight:.15E}")

            if xyz_lines:
                xyz_path = gsd_dir / f"lyr01_frac{fraction_idx:02d}.xyz"
                xyz_path.write_text("\n".join(xyz_lines) + "\n", encoding="utf-8")
                composition_lines.append(f"Fraction{fraction_idx} = gsd_ini_str/lyr01_frac{fraction_idx:02d}.xyz")

    composition_content = "\n".join(composition_lines)

    bed_comp_lines: list[str] = [
        "[BedCompositionFileInformation]",
        "FileVersion = 01.00",
        "FileCreatedBy = sre_convertor",
        "FileCreationDate = autogenerated",
        "",
        "[Fractions]",
    ]
    for idx, d50 in enumerate(fractions, start=1):
        bed_comp_lines.append(f"Fraction{idx}D50 = {d50:.7e}")

    bed_comp_lines.append("")
    for branch_id, weights in summary.branch_composition:
        bed_comp_lines.extend(
            [
                "[Branch]",
                f"branchId = {branch_id}",
                "Type = volume fraction",
            ]
        )
        for idx, weight in enumerate(weights, start=1):
            bed_comp_lines.append(f"Fraction{idx} = {weight:.6f}")
        bed_comp_lines.append("")

    bed_comp_content = "\n".join(bed_comp_lines)

    mor_path.write_text(mor_content, encoding="utf-8")
    sed_path.write_text(sed_content, encoding="utf-8")
    composition_path.write_text(composition_content, encoding="utf-8")
    bed_comp_path.write_text(bed_comp_content, encoding="utf-8")

    return mor_path, sed_path, composition_path, bed_comp_path


def _chainage_to_xy(network: NetworkModel, branch_id: str, chainage: float) -> tuple[float, float] | None:
    """Convert branch/chainage to xy coordinates by linear interpolation between nodes."""
    branch = next((b for b in network.branches if b.id == branch_id), None)
    if not branch:
        return None

    from_node = next((n for n in network.nodes if n.id == branch.from_node_id), None)
    to_node = next((n for n in network.nodes if n.id == branch.to_node_id), None)

    if not from_node or not to_node or branch.length == 0:
        return None

    # Linear interpolation
    ratio = chainage / branch.length
    x = from_node.x + (to_node.x - from_node.x) * ratio
    y = from_node.y + (to_node.y - from_node.y) * ratio
    return x, y


def _get_fraction_weight(summary: MorphodynamicsSummary, branch_id: str, fraction_idx: int) -> float:
    """Get the weight for a specific fraction at a given branch."""
    for bid, weights in summary.branch_composition:
        if bid == branch_id:
            if fraction_idx <= len(weights):
                return weights[fraction_idx - 1]
            return 0.0
    return 0.0
