from __future__ import annotations

from pathlib import Path

from ...models import MorphodynamicsSummary


def write_morphodynamics_files(
    target_dir: Path,
    summary: MorphodynamicsSummary,
) -> tuple[Path, Path, Path, Path]:
    target_dir.mkdir(parents=True, exist_ok=True)

    mor_path = target_dir / "mor.mor"
    sed_path = target_dir / "sed.sed"
    composition_path = target_dir / "mor.composition.ini"
    bed_comp_path = target_dir / "mor.ini"

    fractions = summary.sediment_fractions_d50_m
    if not fractions:
        fallback = summary.representative_d50_m or 0.001
        fractions = (fallback,)

    mor_content = """[MorphologyFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[Morphology]
   MorFac           = 1.0
   MorStt           = 0.0
   Thresh           = 1.0
   BedUpd           = 1
   CmpUpd           = 1
   NeuBcMud         = 0
   NeuBcSand        = 0

[Output]
   Dm               = true
   Dg               = true
   Frac             = true
"""

    sed_blocks: list[str] = []
    for idx, d50 in enumerate(fractions, start=1):
        sed_blocks.extend(
            [
                "[Sediment]",
                f"   Name             = #Sediment{idx}#",
                "   SedTyp           = bedload",
                "   IniSedThick      = 1.0000000e+000",
                "   RhoSol           = 2.6500000e+003",
                "   TraFrm           = 1",
                "   CDryB            = 1.5900000e+003",
                f"   SedDia           = {d50:.7e}",
                "   ACal             = 1.0000000e+000",
                "   RouKs            = 0.000",
                "   SusFac           = 0.000",
                "",
            ]
        )

    sed_content = """[SedimentFileInformation]
   FileCreatedBy    = sre_convertor
   FileCreationDate = autogenerated
   FileVersion      = 02.00

[SedimentOverall]
   Cref             = 1.6000000e+003
""" + "\n".join(sed_blocks)

    composition_lines: list[str] = [
        "[CompositionFileInformation]",
        "FileVersion = 01.00",
        "CreatedBy   = sre_convertor",
        "",
        "[Fractions]",
    ]
    for idx, d50 in enumerate(fractions, start=1):
        composition_lines.append(f"Fraction{idx}D50 = {d50:.7e}")

    composition_lines.append("")
    for branch_id, weights in summary.branch_composition:
        composition_lines.extend(
            [
                "[Branch]",
                f"branchId = {branch_id}",
            ]
        )
        for idx, weight in enumerate(weights, start=1):
            composition_lines.append(f"Fraction{idx} = {weight:.6f}")
        composition_lines.append("")

    composition_content = "\n".join(composition_lines)

    bed_comp_lines: list[str] = [
        "[BedCompositionFileInformation]",
        "FileVersion = 01.00",
        "FileCreatedBy = sre_convertor",
        "FileCreationDate = autogenerated",
        "",
        "[Fractions]",
    ]
    for idx, d50 in enumerate(fractions, start=1):
        bed_comp_lines.append(f"Fraction{idx}D50 = {d50:.7e}")

    bed_comp_lines.append("")
    for branch_id, weights in summary.branch_composition:
        bed_comp_lines.extend(
            [
                "[Branch]",
                f"branchId = {branch_id}",
                "Type = volume fraction",
            ]
        )
        for idx, weight in enumerate(weights, start=1):
            bed_comp_lines.append(f"Fraction{idx} = {weight:.6f}")
        bed_comp_lines.append("")

    bed_comp_content = "\n".join(bed_comp_lines)

    mor_path.write_text(mor_content, encoding="utf-8")
    sed_path.write_text(sed_content, encoding="utf-8")
    composition_path.write_text(composition_content, encoding="utf-8")
    bed_comp_path.write_text(bed_comp_content, encoding="utf-8")

    return mor_path, sed_path, composition_path, bed_comp_path
